#pragma config(Motor,  motorA,          J1,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          J2,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LENGTH 13

float path[LENGTH][2] = {{5.525112,146.789784},
{21.139731,104.477512},
{20.985414,104.477512},
{20.824922,104.477512},
{20.657879,104.477512},
{30.187646,76.702928},
{31.259203,76.702928},
{32.383043,76.702928},
{32.740691,79.824338},
{38.656371,56.632987},
{39.955444,56.632987},
{41.319372,56.632987},
{41.109939,67.045501}
};

void goToTheta(int t1, int t2){
	while(nMotorEncoder[J1]!=t1&&nMotorEncoder[J2]!=t2){
		if(nMotorEncoder[J1] < t1)
				motor[J1] = 25;
		else if(nMotorEncoder[J1] > t1)
				motor[J1] = -25;
		else
				motor[J1] = 0;
		
		if(nMotorEncoder[J2] < t2)
				motor[J2] = 25;
		else if(nMotorEncoder[J2] > t2)
				motor[J2] = -25;
		else
				motor[J2] = 0;
	}
}

task main()
{
	nMotorEncoder[J1] = 0;
	nMotorEncoder[J2] = 180;
	for(int i = 0; i< LENGTH; i++){
		goToTheta((int)path[i][0],	(int)path[i][1]);
	}

}
